version: '3.8'
services:
  short-video-maker:
    image: short-video-maker:1.3.4
    environment:
      - OPENAI_API_KKEY=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
  short-creator:
    build:
      context: .
      dockerfile: main.Dockerfile
    env_file:
      - .env
    environment:
      - DEV=false
    ports:
      - "3123:3123"
    entrypoint: ["node", "dist/index.js"]

